spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 221121

mybatis:
#  type-aliases-package: "com.xxjqr.multiple_modules.core.article.po"
  mapper-locations: "classpath*:com/xxjqr/multiple_modules/mybatis/**/*Mapper.xml"

server:
  port: 8088

